import { cookies } from "next/headers";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import "../globals.css";
import { toast } from "sonner";
import QueryProvider from "./contexts/QueryProvider";
import { ToastContainer } from "react-toastify";
import { getUserFromToken } from "@/utils/GetUserFromToken";
import UserProvider from "./contexts/UserProvider";
import Sidebar from "../components/Sidebar";
import { MenuProvider } from "./contexts/MenuContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Przeniesienie logiki do funkcji async
async function getUser() {
  const cookieStore = cookies();
  const token = (await cookieStore).get("token")?.value;

  if (!token) return null;

  try {
    return await getUserFromToken(token);
  } catch (error) {
    console.error("Error fetching user from token:", error);
    return null;
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser(); // ✅ Teraz jest wewnątrz asynchronicznej funkcji

  return (
    <QueryProvider>
      <MenuProvider>
        <div className="flex-grow ml-0 lg:ml-72">
          <UserProvider user={user} />
          <Sidebar
            isLoggedIn={!!user} // Przekazujemy informację, czy użytkownik jest zalogowany
            userData={
              user
                ? {
                    username: user.username,
                    avatar: user.avatar || "/default-avatar.png",
                  }
                : null
            }
          />
          <main className="flex-grow">{children}</main>
        </div>
        <ToastContainer />
      </MenuProvider>
    </QueryProvider>
  );
}
