import { Inter } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import { MenuProvider } from "./contexts/MenuContext";
import Sidebar from "./components/Sidebar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { cookies } from "next/headers";
import { getUserFromToken } from "@/utils/GetUserFromToken";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const token = (await cookieStore).get("token")?.value; // Pobieramy wartość tokenu
  let user = null;

  if (token) {
    user = await getUserFromToken(token); // Pobieramy użytkownika z tokenu
  }

  return (
    <html lang="en" suppressHydrationWarning className={inter.variable}>
      <body className="font-sans">
        <div className="flex w-auto">
          <MenuProvider>
            <Sidebar isLoggedIn={!!user} user={user} />
            <main className="flex-grow">{children}</main>
          </MenuProvider>
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
