import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import { MenuProvider } from "./contexts/MenuContext";
import Sidebar from "./components/Sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-sans">
        <div className="flex w-auto">
          <MenuProvider>
            <Sidebar />
            <main className="flex-grow">{children}</main>
          </MenuProvider>
        </div>
      </body>
    </html>
  );
}
